name = "ChanceConstraintExtensions"
uuid = "36e31b9c-4f9d-11ea-1ca4-1da90c2f1b64"
authors = ["odow <o.dowson@gmail.com>"]
repo = "https://github.com/osl-northwestern/ChanceConstraintExtensions.jl.git"
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Ipopt", "Test"]
